name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: group:tests:${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: | 
          bunx @biomejs/biome ci &
          bunx tsc --noEmit &
          bun test
          wait

      - name: Notify Status
        if: always()
        run: |
          STATUS_EMOJI="${{ job.status == 'success' && '✅' || '❌' }}"
          STATUS_TEXT="${{ job.status == 'success' && 'white_checkmark' || 'x' }}"

          curl \
            -H "Authorization: Bearer ${{ secrets.NTFY_API_TOKEN }}" \
            -H "Title: Test Results: $STATUS_EMOJI" \
            -H "Tags: test_tube" \
            -H "Priority: ${{ job.status == 'success' && '3' || '5' }}" \
            -H "Click: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}" \
            -H "Markdown: yes" \
            -d "### Test Run Details
            - **Application**: \`${{ github.event.repository.name }}\`
            - **Branch**: \`${{ github.ref_name }}\`
            - **Commit**: [\`${GITHUB_SHA:0:7}\`](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
            - **Run**: [\`${{ github.run_number }}\`](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_number }})

            ${STATUS_EMOJI} Tests **completed** with status: ${{ job.status }}" \
            ${{ secrets.NTFY_URL }}
